name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Go
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/go_service ./m_task_api
          docker push ${{ secrets.DOCKER_USERNAME }}/go_service

      - name: Build and push Python
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/python_client ./python_client
          docker push ${{ secrets.DOCKER_USERNAME }}/python_client

      - name: Build and push Rust
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/rust_service ./rust_service
          docker push ${{ secrets.DOCKER_USERNAME }}/rust_service